name: 'multi-approvers'

on:
  workflow_call:
    inputs:
      org-members-path:
        required: true
        type: string
      multi-approvers-js-url:
        description: 'The URL to multi-approvers.js. This should typically not need to be set.'
        type: string
        default: 'https://raw.githubusercontent.com/ian-shafer/playground/main/.github/workflows/multi-approvers.js'

permissions:
  actions: 'write'
  contents: 'read'
  pull-requests: 'read'

jobs:
  multi-approvers:
    if: contains(fromJSON('["pull_request", "pull_request_review"]'), github.event_name)
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout calling repo'
        uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4

      - name: 'Download multi-approvers.js'
        id: 'download-multi-approvers-js'
        run: |-
          MULTI_APPROVERS_JS="${RUNNER_TEMP}/${GITHUB_SHA:0:7}.multi-approvers.js"

          # Download the file, passing in authentication to get a higher rate
          # limit: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
          curl "${{ inputs.multi-approvers-js-url }}" \
            --silent \
            --fail \
            --location \
            --header "Authorization: Token ${{ github.token }}" \
            --output "${MULTI_APPROVERS_JS}"

          # Save the result to an output.
          echo "::notice::Downloaded multi-approvers.js to ${MULTI_APPROVERS_JS}"
          echo "output-file=${MULTI_APPROVERS_JS}" >> "${GITHUB_OUTPUT}"

      - name: 'Check approver requirements'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          retries: 3
          script: |-
            const orgMembersPath = '${{ github.workspace }}/${{ inputs.org-members-path }}';
            const prNumber = ${{ github.event.pull_request.number }}
            const repoName = '${{ github.event.repository.name }}'
            const repoOwner = '${{ github.event.repository.owner.login }}'
            const {onPullRequest} = require('${{ steps.download-multi-approvers-js.outputs.output-file }}');
            const baseDir = '';
            await onPullRequest({
              orgMembersPath,
              prNumber,
              repoName,
              repoOwner,
              github,
              core,
            });
      - name: 'Re-run approver checks'
        if: github.event_name == 'pull_request_review'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          retries: 3
          script: |-
            const branch = '${{ github.event.pull_request.head.ref }}'
            const prNumber = ${{ github.event.pull_request.number }}
            const repoName = '${{ github.event.repository.name }}'
            const repoOwner = '${{ github.event.repository.owner.login }}'
            const workflowRef = '${{ github.workflow_ref }}';
            const {onPullRequestReview} = require('${{ steps.download-multi-approvers-js.outputs.output-file }}');
            await onPullRequestReview({
              branch,
              prNumber,
              repoName,
              repoOwner,
              workflowRef,
              github,
              core,
            });
