name: 'multi-reviewers'

on:
  push:
  pull_request:
    types:
      - 'opened'
      - 'edited'
      - 'ready_for_review'
      - 'review_requested'
  pull_request_review:
    types:
      - 'submitted'
      - 'dismissed'
  workflow_call:
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  actions: 'write'
  pull-requests: 'read'

jobs:
  multi-reviewers:
    runs-on: 'ubuntu-latest'
    steps:
      - id: 'xxx'
        name: 'Xxx'
        uses: 'actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea' # ratchet:actions/github-script@v7
        with:
          retries: 3
          script: |-
            const name = "Ian Shafer";
            //core.setFailed("I never work!");
